name: quick_quotes_quill
description: Simple logger package.
  You can create your own loggers (quills) by implementing QuillBase.
  Also package has one implementation of QuillBase - ConsoleQuill.
  This class prints colorized logs.
  You can customize ConsoleQuill by changing colors.
  More than that you can manage quills with QuillManagerBase.
  Just create implementation or use SpreadQuillManager, AccessQuillManager.
  SpreadQuillManager gives each log to all quills.
  AccessQuillManager provides certain quill by its name.
version: 1.1.0
homepage: https://github.com/bytes7bytes7/quick_quotes_quill

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
