name: quick_quotes_quill
description: Logger package
version: 1.0.0
homepage: https://github.com/bytes7bytes7/quick_quotes_quill

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
