name: quick_quotes_quill
description: Simple logger package.
  Create your loggers (quills) by implementing QuillBase or use ConsoleQuill.
  Manage quills by implementing QuillManagerBase or use SpreadQuillManager, AccessQuillManager.
version: 2.0.0
homepage: https://github.com/bytes7bytes7/quick_quotes_quill

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
