name: quick_quotes_quill
description: Simple logger package.
  Create loggers (quills) by implementing Quill.
  Manage quills by implementing QuillManager.
version: 3.0.0
homepage: https://github.com/bytes7bytes7/quick_quotes_quill

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  archive: ^3.3.0
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
